stages:
  - deploy

deploy-job:
  stage: deploy
  tags:
    - runner_1
  script:
    - echo $PRIVATE_KEY | base64 -d >> private_key
    - chmod 400 private_key
    - echo $RANDOM | md5sum | head -c 20 > name.txt
    - echo "sh ~/runner_helper_hs $(cat name.txt)" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - echo "sed -i 's|https://hobbyshare.app:8000|https://test.hobbyshare.app:8000|g' ~/$(cat name.txt)/Front/src/app/api.service.ts" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - echo "cd ~/$(cat name.txt)/Front && export PATH=/home/deploy/.nvm/versions/node/v14.17.5/bin:$PATH && yarn install && yarn ng build" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - echo "rm -rf /var/www/hobbyshare-test && cp -r ~/$(cat name.txt)/Front/dist /var/www/hobbyshare-test" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - echo "rm -rf ~/hobbyshare && cp -r ~/$(cat name.txt)/Back ~/hobbyshare && cd ~/hobbyshare && python3 -m venv env && . env/bin/activate && pip install -r requirements.txt && . ~/run_server" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - echo "rm -rf /etc/nginx/sites-enabled/hs-test && cp ~/$(cat name.txt)/test-config /etc/nginx/sites-enabled/hs-test && sudo /usr/sbin/service nginx restart; rm -rf ~/$(cat name.txt)" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - eval `ssh-agent -s` && ssh-add -D
    - rm private_key
