# Generated by Django 3.1.3 on 2020-11-18 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=30)),
                ('skills', models.TextField()),
                ('profilepic', models.ImageField(null=True, upload_to='profilepics')),
                ('projects', models.TextField(null=True)),
                ('contributing', models.TextField(null=True)),
                ('sessionid', models.TextField(null=True)),
                ('token', models.TextField(null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('plan', models.TextField()),
                ('skills', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contributors', models.TextField(null=True)),
                ('res1', models.ImageField(null=True, upload_to='resource1')),
                ('res2', models.ImageField(null=True, upload_to='resource2')),
                ('requests', models.TextField(null=True)),
                ('invites', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
